package com.myspace.candidates;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Competitions implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Competition Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Competition ID")
	private java.lang.String id;

	public Competitions() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Competitions(java.lang.String name, java.lang.String id) {
		this.name = name;
		this.id = id;
	}

}