package com.myspace.candidates;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Interests implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Interests() {
    }




}