package com.myspace.candidates;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Profile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Work Phone Number")
	private java.lang.String workNumber;
	@org.kie.api.definition.type.Label("Home  / Mobile Phone Number")
	private java.lang.String otherNumber;
	@org.kie.api.definition.type.Label("E-mail")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Veterinary Council Number")
	private java.lang.String vetCouncilNumber;
	@org.kie.api.definition.type.Label("Home Address")
	private java.lang.String homeAddress;
	@org.kie.api.definition.type.Label("Correspondence Address")
	private java.lang.String otherAddress;
	@org.kie.api.definition.type.Label("Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label("Date Of Birth")
	private java.lang.String dob;
	@org.kie.api.definition.type.Label("Special Facilities")
	private java.lang.Boolean specialFacilities;
	@org.kie.api.definition.type.Label("Special Facilities Details")
	private java.lang.String specialFacilitiesDetails;

	@org.kie.api.definition.type.Label("Interests")
	private com.myspace.candidates.Interests interests;

	public Profile() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getWorkNumber() {
		return this.workNumber;
	}

	public void setWorkNumber(java.lang.String workNumber) {
		this.workNumber = workNumber;
	}

	public java.lang.String getOtherNumber() {
		return this.otherNumber;
	}

	public void setOtherNumber(java.lang.String otherNumber) {
		this.otherNumber = otherNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getVetCouncilNumber() {
		return this.vetCouncilNumber;
	}

	public void setVetCouncilNumber(java.lang.String vetCouncilNumber) {
		this.vetCouncilNumber = vetCouncilNumber;
	}

	public java.lang.String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(java.lang.String homeAddress) {
		this.homeAddress = homeAddress;
	}

	public java.lang.String getOtherAddress() {
		return this.otherAddress;
	}

	public void setOtherAddress(java.lang.String otherAddress) {
		this.otherAddress = otherAddress;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getDob() {
		return this.dob;
	}

	public void setDob(java.lang.String dob) {
		this.dob = dob;
	}

	public java.lang.Boolean getSpecialFacilities() {
		return this.specialFacilities;
	}

	public void setSpecialFacilities(java.lang.Boolean specialFacilities) {
		this.specialFacilities = specialFacilities;
	}

	public java.lang.String getSpecialFacilitiesDetails() {
		return this.specialFacilitiesDetails;
	}

	public void setSpecialFacilitiesDetails(
			java.lang.String specialFacilitiesDetails) {
		this.specialFacilitiesDetails = specialFacilitiesDetails;
	}

	public com.myspace.candidates.Interests getInterests() {
		return this.interests;
	}

	public void setInterests(com.myspace.candidates.Interests interests) {
		this.interests = interests;
	}

	public Profile(java.lang.String name, java.lang.String workNumber,
			java.lang.String otherNumber, java.lang.String email,
			java.lang.String vetCouncilNumber, java.lang.String homeAddress,
			java.lang.String otherAddress, java.lang.String gender,
			java.lang.String dob, java.lang.Boolean specialFacilities,
			java.lang.String specialFacilitiesDetails,
			com.myspace.candidates.Interests interests) {
		this.name = name;
		this.workNumber = workNumber;
		this.otherNumber = otherNumber;
		this.email = email;
		this.vetCouncilNumber = vetCouncilNumber;
		this.homeAddress = homeAddress;
		this.otherAddress = otherAddress;
		this.gender = gender;
		this.dob = dob;
		this.specialFacilities = specialFacilities;
		this.specialFacilitiesDetails = specialFacilitiesDetails;
		this.interests = interests;
	}

}